### ISSUE TITLE
"Cannot be opened, must be deleted" Error even in Safari

### ISSUE THREAD

**Issue by Jeiji** [vpeschenkov/Predator#12]
No matter what I do, I can't seem to download it, and it always throws that same error.

I'm on a 2019 "15 MacBook Pro, on 10.14.6 (Mojave)

**Comment by vpeschenkov** [comment]
Hi @Jeiji,

Sorry for this and thank you for the feedback. It seems like the issues with Gatekeeper appeared again...

I could fix it now but after some time it will arise again. So I'm gonna publish it to the App Store and sign it by an Apple developer key to omit this in the future.

I think I'll have done this by this weekend and after there shouldn't be such kind an issue. And then you will be able to use it. I let you know 🙂

Thank you!

**Comment by vpeschenkov** [comment]
Hi @Jeiji, I updated it with the normal developer ID. Now it should work. Could you download the [latest release](https://github.com/vpeschenkov/Predator/releases/download/1.0.6/Predator.saver.zip)?

**Comment by Jeiji** [comment]
It worked! Thanks so much for keeping on it.
