### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by corybrewis** [vpeschenkov/Predator#9]
Thanks for making this, its super cool! I love the Predator clock Idea and how you implemented it, good work! I was wondering if it was possible to make a feature that would allow the user to be able to completely blackout the non filled shapes when displaying the time, or possibly the option to make the non filled shapes a different color than the filled shapes, which then I would be able to change the color to black myself?
![preview2](https://user-images.githubusercontent.com/35346313/58438749-549b9980-8085-11e9-83a5-5aa800705f2e.png)

**Comment by vpeschenkov** [comment]
Hi @corybrewis, thank you for your feedback. I was thinking about this but decided to not add this feature due to some reasons in my head. However, I can't remember them 🙂. So, I'll add this feature and let you know!

**Comment by corybrewis** [comment]
@vpeschenkov  That would be awesome! Thank you!

**Comment by vpeschenkov** [comment]
@corybrewis Updated. Will appreciate if you try it 🙂
